CREATE TABLE EMP_1(
EMP_NUM CHAR(3),
EMP_Lname VARCHAR(15),
EMP_Fname VARCHAR(15),
EMP_INITIAL CHAR(1),
EMP_HIREDATE DATE,
JOB_CODE CHAR(3));

SELECT * FROM EMP_1 WHERE JOB_CODE = '502';
INSERT INTO EMP_1 (EMP_NUM, EMP_Lname, EMP_Fname, EMP_INITIAL, EMP_HIREDATE, JOB_CODE) VALUES ('07', 'David', 'Dymphna', 'D', '2003-04-05', '502' )

